CREATE SCHEMA IF NOT EXISTS PROJECT_DB.TASKS;

CREATE OR REPLACE TASK PROJECT_DB.TASKS.CLEAN_EMPLOYEES_TASK
WAREHOUSE = COMPUTE_WH
AS
CREATE OR REPLACE TABLE PROJECT_DB.CLEAN.CLEAN_EMPLOYEES AS
SELECT
    ID,
    NULLIF(NAME, '') AS NAME,
    INITCAP(DEPARTMENT) AS DEPARTMENT,
    TRY_TO_NUMBER(SALARY) AS SALARY,
    TRY_TO_DATE(JOIN_DATE) AS JOIN_DATE
FROM PROJECT_DB.RAW.RAW_EMPLOYEES_STAGE;
