CREATE OR REPLACE TASK PROJECT_DB.TASKS.CURATED_EMPLOYEE_ANALYTICS_TASK
WAREHOUSE = COMPUTE_WH
AFTER PROJECT_DB.TASKS.CLEAN_EMPLOYEES_TASK
AS
CREATE OR REPLACE TABLE PROJECT_DB.CURATED.EMPLOYEE_ANALYTICS AS
SELECT
    ID,
    NAME,
    DEPARTMENT,
    SALARY,
    JOIN_DATE,
    DATEDIFF(DAY, JOIN_DATE, CURRENT_DATE()) AS DAYS_SINCE_JOIN,
    CASE WHEN SALARY >= 80000 THEN 1 ELSE 0 END AS IS_HIGH_EARNER,
    DENSE_RANK() OVER (
        PARTITION BY DEPARTMENT
        ORDER BY SALARY DESC
    ) AS DEPT_SALARY_RANK
FROM PROJECT_DB.CLEAN.CLEAN_EMPLOYEES
WHERE SALARY IS NOT NULL;